### ISSUE TITLE
The response for resource had empty or invalid content.

### ISSUE THREAD

**Issue by IUnknownPtr** [Azure/azure-resource-manager-schemas#1010]
I have a streaming endpoint in ARM template:

```json
{
    "name": "[concat(variables('mediaServiceName'), '/2')]",
    "type": "Microsoft.Media/mediaservices/streamingEndpoints",
    "apiVersion": "2018-07-01",
    "location": "[resourceGroup().location]",
    "properties": {
        "cdnEnabled": true,
        "scaleUnits": 0,
        "cdnProvider": "StandardVerizon",
        "cdnProfile": "dev-cdn-media"
    },
    "dependsOn": [
        "[resourceId('Microsoft.Media/mediaServices', variables('mediaServiceName'))]"
    ]
}

```

Deploying this template fails with error message:
```

Line |
  48 |  New-AzResourceGroupDeployment -Name "Deployment-$($Now.ToString('yyyy …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 6:08:45 PM - Resource Microsoft.Resources/deployments 'Deployment-2020-05-18-180813-Template-007' failed with message '{   "status": "Failed",   "error": {     "code": "ResourceDeploymentFailure",
     | "message": "The resource operation completed with terminal provisioning state 'Failed'.",     "details": [       {         "code": "DeploymentFailed",         "message": "At least one resource deployment
     | operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",         "details": [           {             "code": "InternalServerError",
     | "message": "{\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The response for resource had empty or invalid content.\"\r\n  }\r\n}"           }         ]       }     ]
     | } }'
```

Despite errors streaming endpoint was created and properly configured. The consecutive deployments of the same template fail with another error: 

```
Line |
  48 |  New-AzResourceGroupDeployment -Name "Deployment-$($Now.ToString('yyyy …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 6:47:20 PM - Resource Microsoft.Media/mediaservices/streamingEndpoints 'devmedia/2' failed with message '{   "error": {     "code": "ResourceNameTaken",     "message": "Origin with the same name already
     | exists."   } }'
```

Two questions:

1. Is it a known bug with configuring streaming endpoint via ARM template?
2. Why the deployment in this case is not idempotent?

**Comment by johndeu** [comment]
@IUnknownPtr  - if this is not a schema issue, which it does not appear to be, I recommend closing the issue here and taking the discussion over to our new Q&A area in Azure documentation for Media Services.  
https://docs.microsoft.com/en-us/answers/topics/azure-media-services.html

the first error you received is an internal server error which indicates something wrong in either ARM or Streaming RP service.  We should ask the team to investigate that. Would be good to get the details from your account on this.  Are you also able to open a ticket in the portal with the details? Team will want to know account name, subscription ID, etc, and time period of issue.  That will help them diagnose. Best way to get that is filing a ticket in the account in the Azure portal.

**Comment by anthony-c-martin** [comment]
Closing as this appears to be a service issue. Please see the above comment.

**Comment by IUnknownPtr** [comment]
@johndeu the ticket was open for **3 months** in Azure Portal and support closed it without any workarounds! Good job!

**Comment by apclouds** [comment]
Adding @akucer from the Media team.
