### ISSUE TITLE
Microsoft.network/networkinterfaces template reference specifies that location is not required

### ISSUE THREAD

**Issue by sean-keane25** [Azure/azure-resource-manager-schemas#1024]
The Microsoft.network/networkinterfaces template reference specifies that location is not required but the schema indicates that it is required. I have tried to create a NIC with a null location on all available API versions and it was not allowed. The template reference should be updated to reflect whats specified in the schema.

[Microsoft.Network networkInterfaces template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/networkinterfaces)

[Microsoft.Network schema](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2020-04-01/Microsoft.Network.json#L1573)

**Comment by alex-frankel** [comment]
@tfitzmac - can we take a look at our autogen logi for the template reference?

**Comment by sean-keane25** [comment]
Any updates on this ?

**Comment by tfitzmac** [comment]
The problem is in the swagger file. Location is not marked as required. They use a shared [resource definition](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/network.json#L156) which means most networking resource types have location as not required. I am guessing the schema process overrides this value, which is probably what I should do for template reference too. I'll create an item for myself.

**Comment by apclouds** [comment]
@tfitzmac once the doc has been updated let me know so I can close this issue.

**Comment by tfitzmac** [comment]
@sean-keane25 - thanks for making me aware of this issue. It has been fixed in the generation process. The docs now should show location as required.

**Comment by tfitzmac** [comment]
@apclouds - this issue can be closed.
