### ISSUE TITLE
Missing auto-completion for Storage Account Type

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#138]
Using Visual Studio Code Insiders v0.10.15-insider.

![image](https://cloud.githubusercontent.com/assets/466713/14473888/8a81a46e-00b7-11e6-8fcf-ed46bd5c25f0.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by rjmax** [comment]
Storage team has booked this fix for May.

**Comment by jonsabo** [comment]
Looks like this was fixed in `2016-01-01` at least, so guessing this can be closed:

https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2016-01-01/Microsoft.Storage.json#L188-L194
```
              "enum": [
                "Standard_LRS",
                "Standard_GRS",
                "Standard_RAGRS",
                "Standard_ZRS",
                "Premium_LRS"
              ]
```


and in VS code

![storageacct](https://cloud.githubusercontent.com/assets/1638148/19570095/11a91cb4-96be-11e6-92e2-a3bc3f1b1846.png)
