### ISSUE TITLE
Storage Account Export Template - SKU object on blobServices resource

### ISSUE THREAD

**Issue by miqm** [Azure/azure-resource-manager-schemas#1460]
@anthony-c-martin - I know this repository is not for tracking issues with Azure Portal export template functionality, but it's hard to find where such issues can be reported.

To the point:
When you export storage account template, you get (among other resources) following one:

```
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_name'))]"
            ],
            "sku": {
                "name": "Standard_LRS",
                "tier": "Standard"
            },
            "properties": {
                "cors": {
                    "corsRules": []
                },
                "deleteRetentionPolicy": {
                    "enabled": false
                }
            }
        },
```
Thing is, that "sku" property is not part of the blobServices definiton and basically - it's odd to put it there, as I'm not quite aware, that you can define different SKU for blob services - I thought SKU is defined for entire Storage Account.

So either definition (https://github.com/Azure/azure-resource-manager-schemas/blob/6935382d0b23b37ec4d3fde559c8018f55030497/schemas/2020-08-01-preview/Microsoft.Storage.json#L154) is wrong, or exporting function is faulty.

**Comment by anthony-c-martin** [comment]
Thanks for raising this! The resource provider returns the SKU as a readonly property (definition [here](https://github.com/Azure/azure-rest-api-specs/blob/44ec11c74634f1afa5bbe0d3f2678b7f819ebf8e/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/blob.json#L1215)), but the backend Export algorithm does not strip any top-level resource properties based on schema structure - only items inside the "properties" object.

I've added an issue for this to the taskboard we use internally to track ARM service issues, and we'll discuss this there. Since the schema appears correct here, I'll close this issue out and use the internal issue to track.
