### ISSUE TITLE
Microsoft.Network/frontdoors/frontendEndpoints/customHttpsConfiguration schema missing

### ISSUE THREAD

**Issue by Bab95** [Azure/azure-resource-manager-schemas#2098]
Schema for this resource is not available but i can see this resource in the swagger docs. Is there a bug in the generator.

**Comment by anthony-c-martin** [comment]
@Bab95 would you mind giving a pointer to where you see this resource in the swagger docs?

I could only find references to a POST action (example [here](https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-04-01/frontdoor.json#L492)) - ARM Templates only support PUTable resources, and not operations submitted via POST.

**Comment by anthony-c-martin** [comment]
Responded offline on Teams:

So looks like there's a read-only property named customHttpsConfiguration on the frontendEndpoints resource. It's not present in the schema because it has been marked as read-only: https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-04-01/frontdoor.json#L1461-L1465

There's what looks like a POST action defined on the frontendEndpoints, which you can use to set it: https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-04-01/frontdoor.json#L492

ARM Template JSON does not allow you to invoke POST actions however.

I think you'll need to follow up with the Microosft.Network team to understand if there is some way to invoke this API through an ARM template

**Comment by anthony-c-martin** [comment]
Closing as this isn't an issue with template schemas.
