### ISSUE TITLE
Unable to load schema from 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json'. No schema request service available

### ISSUE THREAD

**Issue by shubhie267** [Azure/azure-resource-manager-schemas#2244]
![image](https://user-images.githubusercontent.com/39084244/157404457-6ce9d19d-b1ca-4c50-8a9e-c39cedabac81.png)

**Comment by jorgecotillo** [comment]
This is a Portal issue, @stephaniezyen do we have a Portal contact? I just tried now and seems like the schemas are not recognized. Please not that this is not a blocking issue because the intent is not to use the Portal to author a template instead you can either use Visual Studio or VSCode (using ARM VSCode extension).

I'll close this issue for now since is not schemas related, we'll try to do our best to get this fixed but since authoring an ARM template is not meant to be performed in this UI I am unsure whether or not the Portal team will fix this.
