### ISSUE TITLE
ServiceBus Queue/Topic/Subscription multiple segment name problem

### ISSUE THREAD

**Issue by xtomas** [Azure/azure-resource-manager-schemas#230]
Hi,

when using ARM template 2015-08-01 with deployment template 2015-01-01, I'm not able to create Queues and Subscriptions with "multiple segments name". For example "system1/queuename", "system1/topicname"...

When used, I receive error about more segments in name than in resource type.

Our ServiceBus structure is used for more than year in production mode so rename is not easy task.

Is there any way how to create queue with name "system1/queuename" using ARM template?

Tomas

**Comment by antmarti-microsoft** [comment]
@xtomas Can you please try using a '\~' character instead of a '/'. '/' is reserved in Azure Resource Manager, and is not valid as part of a resource name. It appears that the ServiceBus UI works around this by replacing '/' with '\~' when creating the resource.

As this is an old issue, I'm going to close this, but please re-open if this is still a problem.
