### ISSUE TITLE
Missing Schema for "Microsoft.Web/hostingEnvironments"

### ISSUE THREAD

**Issue by MattAllison** [Azure/azure-resource-manager-schemas#346]
I'm using VSCode for editing ARM templates.  

For "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json", it reports that "type": "Microsoft.Web/hostingEnvironments" is not a valid value.

**Comment by leidegre** [comment]
@MattAllison there's a lot of things that show up as wrong or isn't recognized when you edit templates that way, doesn't mean that is wrong, just that the schema isn't perfect. Use the validate template from PowerShell cmdlets or Azure CLI 2.0 to test whether that you put in actually works.

~~~
Test-AzureRmResourceGroupDeployment -ResourceGroupName <resource-group> -TemplateFile .\azuredeploy.json -Debug
~~~

Azure CLI 2.0 (IMAO preferred because the output is the validated JSON object and you don't get prompted 10 times)

~~~
az group deployment validate -g <resource-group> --template-file azuredeploy.json
~~~

**Comment by ifeoluwaokunoren** [comment]
Closing issue - please open a new issue if you're still facing any difficulties.
