### ISSUE TITLE
Missing Schema : Microsoft.RecoveryServices/vaults/backupPolicies

### ISSUE THREAD

**Issue by jeffpatton1971** [Azure/azure-resource-manager-schemas#399]
Team,

Can we get this added in? It would be nice to have the scheme as a reference when building out custom solutions.

Also, it appears to be available in at least two api versions?

2015-10-11
2016-06-01

Please confirm that this is correct and update accordingly.

**Comment by pvrk** [comment]
@jeffpatton1971 : Not sure if this is what you were looking for:

![image](https://user-images.githubusercontent.com/17268738/136146543-88452ccd-bca3-4854-a8a5-9b20615368f5.png)

**Comment by anthony-c-martin** [comment]
I think this issue has since been fixed with #1451. We currently have this resource available in these versions: https://github.com/Azure/azure-resource-manager-schemas/blob/52a0fdd4c8f69c039f68ddcbb89543419114e3a1/generator/resources.json#L6064-L6079

@jeffpatton1971 - please reopen if you disagree.
