### ISSUE TITLE
Documentation on 2015-01-01 

### ISSUE THREAD

**Issue by AlexKeySmith** [Azure/azure-resource-manager-schemas#403]
Hi,

It would be great to have some official docs (wiki or readme perhaps?) on the background to the porting back to 2015-01-01.

And perhaps a little reference saying it's the latest version for ease of use.

I'm sure the regular visual studio user looks at the schema reference 2015-01-01 and thinks to themselves; "I'm using an old version" whereas they are not, leading to confusion.

Perhaps also some info on if everything ends up back in 2015-01-01 or just non-breaking changes, as I can see e.g. there are multiple schemas for storage in 2015-01-01.

**Comment by ifeoluwaokunoren** [comment]
The version relates to the structure of the schema itself, and since this structure has not had any breaking changes since 2015-01-01 was published, there has been no reason to increment it. We'll add some documentation to this repo to explain this is the latest version.

Public docs referencing this version can be found here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#template-format
