### ISSUE TITLE
subscriptionDeploymentTemplate.json - Missing definition: Microsoft.Resources/resourceGroups

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-resource-manager-schemas#715]
Subscription level schema does not recognize the resource type "Microsoft.Resources/resourceGroups". Looks(?) like it is not referenced correctly in the schema. See screenshot of error
![SubscriptionDeployment_ResourceGroupDefinition](https://user-images.githubusercontent.com/28310425/65534651-e5687180-decd-11e9-8da2-149f36a4bb32.png)

**Comment by anthony-c-martin** [comment]
Looks like this is occurring because the `Microsoft.Resource/resourceGroups` resource hasn't declared the `name` property as a valid template expression - the JSON schema is failing to match against this resource type because the regular expression match fails (see https://github.com/Azure/azure-resource-manager-schemas/blob/926081eedc19faddbe0f5fd2ecc9a28488074358/schemas/2018-05-01/Microsoft.Resources.json#L10-L15).

One of the problems when doing a JSON schema match is that every property is treated as equal when attempting to match your resource against the known set of resources - so rather than suggesting that there's an error with the `name` field (which seems like the logical thing to do), it's finding the resource which most closely matches yours (in this case, `Microsoft.Authorization/policyAssignments`) and suggesting the simplest change to make it match. Ideally the schema matching should prioritize certain properties such as type & apiVersion when matching.

I'll fix up the resourceGroups definition (which should resolve this issue), and will also discuss internally if we can improve this behavior in VSCode's schema matching engine.

**Comment by CHDAFNI-MSFT** [comment]
Thanks Anthony. I actually see this issue with multiple resource types. Should I be creating a new issue for each one?

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by StephenWeatherford** [comment]
I think this is fixed.

**Comment by anthony-c-martin** [comment]
Addressed by https://github.com/Azure/azure-resource-manager-schemas/pull/822
