### ISSUE TITLE
How do you actually use the generator?

### ISSUE THREAD

**Issue by jlian** [Azure/azure-resource-manager-schemas#760]
When I try to generate a schema for IoT Hub by using `npm run generate-single iothub/resource-manager` as instructed, this is the kind of output I see

```
================================================================================================================================
[C:\Users\jlian\Documents\Repos\azure-resource-manager-schemas\generator] executing: autorest-beta.cmd --azureresourceschema --azureresourceschema.multi-scope=true --output-folder=C:\Users\jlian\AppData\Local\Temp\n79h800f0m8 --tag=all-api-versions --api-version=2019-03-22 --title=none C:\Users\jlian\AppData\Local\Temp\schm_azspc\specification\iothub\resource-manager\readme.md
AutoRest code generation utility [version: 3.0.6116; node: v10.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\jlian\Documents\Repos\azure-resource-manager-schemas\generator\node_modules\@autorest\core\dist' (3.0.6121)
   Loading local AutoRest extension '@autorest/azureresourceschema' (C:\Users\jlian\Documents\Repos\azure-resource-manager-schemas\generator\node_modules\@autorest\azureresourceschema)
[15.09 s] Generation Complete
================================================================================================================================
Filename: C:\Users\jlian\AppData\Local\Temp\n79h800f0m8\2019-03-22\Microsoft.Devices.json
Provider Namespace: Microsoft.Devices
API Version: 2019-03-22
Resource Types (Resource Group Scope):
- IotHubs
- IotHubs/certificates
- IotHubs/eventHubEndpoints/ConsumerGroups
================================================================================================================================
```

So I'm like, great, the output is at `C:\Users\jlian\AppData\Local\Temp\n79h800f0m8\2019-03-22\Microsoft.Devices.json`, let me go get my file. And then this is what I get

![image](https://user-images.githubusercontent.com/2320572/66692023-6b671500-ec4f-11e9-9359-d3a6f0021623.png)

So I thought to myself, ok, it's a temp folder so it may have been deleted already, so I go to `C:\Users\jlian\AppData\Local\Temp` to monitor it while running `npm run generate-single iothub/resource-manager`. But as I do that and the command is running, I never see *any* of the folders that it said it would output to (e.g. `--output-folder=C:\Users\jlian\AppData\Local\Temp\n79h800f0m8`) show up. The only things that would show up would be like a folder called `autorest-yJvADY` and inside there are no JSON files:

![image](https://user-images.githubusercontent.com/2320572/66692064-ca2c8e80-ec4f-11e9-9157-2aa4c0cec2a8.png)

**So how do you actually get the output JSON schema?** What am I doing wrong? I checked the docs already, and all it said was "Save the output to file" - but how?

**Comment by anthony-c-martin** [comment]
@jlian You're totally correct - that's a temporary file which is moved during processing. The logging takes place before it's been moved, which is why you can't find the file. I'll see if I can improve this logging to actually give the correct final file path.

Note that all of the schema changes are made in-place in the repo. The temporary file is generated, then moved into the appropriate folder in the schemas repo, and referenced from the `autogeneratedResources.json` file. So you should be able to run a `git diff` after running the `generate-single` command to see the set of schema changes made by the generation process. If you aren't seeing any changes, then it may just be that your schema is already fully up-to-date. The 'output' referenced in the README is just the stdout (anything you see logged to console), as it just allows the PR reviewer to ensure that nothing unexpected happened.

Note that we have two recommended processes for ensuring your schemas are up-to-date. The first (which it seems like you're following) is documented [here](https://github.com/Azure/azure-resource-manager-schemas#instructions) - any time a change is required, your team would need to follow these steps. The second (documented [here](https://github.com/Azure/azure-resource-manager-schemas/tree/master/generator#onboarding-teams-to-autogeneration-pipeline)) allows teams to follow a one-time onboarding process - after which ARM will automatically pick up changes and regenerate schemas on a daily basis.

Right now we're trying to move teams towards the second option as it requires less manual work for both of us in the long run; if you're interested or have any further questions, feel free to ping me internally - my alias is antmarti.

**Comment by jlian** [comment]
> Note that all of the schema changes are made in-place in the repo

Oooohhh I see, I was so fixated on the output file path as shown that I didn't even think this would be the case.

I checked git diff and can see that the files have indeed been changed. Do you think you could make it more obvious in your instructions?

Let me see if I can do the one-time onboarding thing

**Comment by anthony-c-martin** [comment]
FYI I've improved the file path logging, and specified "console output" instead of just "output" with this change:
https://github.com/Azure/azure-resource-manager-schemas/pull/757/commits/22e2e4e7447ccd624a5d517faf2181f6b7a86d96
