### ISSUE TITLE
SQL Server (2019-06-01-preview) schema missing child resources

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-resource-manager-schemas#964]
Looking at the SQL Server `2019-06-01-preview` schema, the only defined child resources are `administrators` and `databases`.

https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-06-01-preview/Microsoft.Sql.json#L105

SQL server includes other child resources such as `firewallRules`. Because `firewallRules` is missing from the schema, schema validation is failing in ARM Tools.

![image](https://user-images.githubusercontent.com/7844635/77255985-9dca6480-6c28-11ea-8a75-eb99a0ae84d2.png)

To contrast, the SQL Server `2014-04-01` schema has 10 defined child resources for SQL Server.

https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2014-04-01/Microsoft.Sql.json#L35

Why does the` 2019-06-01-preview` schema only include a subset of available child resources?

I've opened this issue specific to SQL Server but am concerned that many resources may have the same issue.

**Comment by anthony-c-martin** [comment]
Note - I believe this is related to https://github.com/Azure/azure-resource-manager-schemas/issues/897.

If an RP is publishing a new API version spec, some teams will only publish the changed resource types - I believe to avoid unnecessary duplication.

However, since the autorest tool runs against a particular API version, relative references (e.g. parent -> child relationships) are only resolved within this API version, yet ARM does not actually require child resource API versions to match those of the parent. Will discuss some potential solutions to this offline.

**Comment by anthony-c-martin** [comment]
Closing this issue as we've already got https://github.com/Azure/azure-resource-manager-schemas/issues/897 to track the more general issue. Whatever solution we come up with should apply to all resource types.
